#!/usr/bin/env node
/**
 * Builds the web app as static files for the Android APK.
 *
 *   node scripts/build-app-web.mjs https://your-app.vercel.app
 *
 * Output: android-app/dist/  (Capacitor's webDir) — the whole app, exported as static HTML/JS,
 *   calling the API at the given deployment (lib/api.ts). Since Mehr 1405 there is one app: the
 *   earlier phone-only screens (price alerts, per-device live trading, the game, automatic SMS
 *   reading) are pages of it, and their data is carried over (lib/finance/migrate.ts).
 *
 * The site itself is server-rendered and has API routes, neither of which a static export can
 * hold. So the export runs on a copy of the sources in .app-build/ with three changes: no
 * app/api, no middleware, and a layout that does not fetch the snapshot on the server (the client
 * fetches it, and keeps the last one on the phone). Every change is an exact string replacement
 * that fails loudly if the source moved on, so the APK cannot silently drift from the site.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TMP = join(ROOT, '.app-build');
const DIST = join(ROOT, 'android-app', 'dist');

const base = (process.argv[2] || process.env.BOARD_URL || '').trim().replace(/\/$/, '');
// http only for a local test server; Android blocks cleartext traffic to anything else
if (!/^https:\/\/[\w.-]+/.test(base) && !/^http:\/\/localhost(:\d+)?$/.test(base)) {
  console.error('usage: node scripts/build-app-web.mjs https://your-app.vercel.app  (https required)');
  process.exit(1);
}

function replaceExact(text, from, to, what) {
  if (!text.includes(from)) {
    console.error(`build-app-web: could not find ${what} in app/layout.tsx — update this script to match the layout.`);
    process.exit(1);
  }
  return text.replace(from, to);
}

// 1) a copy of the sources, without what a static export cannot contain
rmSync(TMP, { recursive: true, force: true });
mkdirSync(TMP, { recursive: true });
for (const p of ['app', 'components', 'lib', 'types', 'public', 'package.json', 'tsconfig.json', 'next-env.d.ts']) {
  if (existsSync(join(ROOT, p))) cpSync(join(ROOT, p), join(TMP, p), { recursive: true });
}
rmSync(join(TMP, 'app', 'api'), { recursive: true, force: true });
// the SMS parser and the game engine are plain JS shared with the Android tests, imported by path
mkdirSync(join(TMP, 'android-app', 'www'), { recursive: true });
for (const f of ['sms-parser.js', 'game-engine.js']) cpSync(join(ROOT, 'android-app', 'www', f), join(TMP, 'android-app', 'www', f));

// 2) a layout without the server-side snapshot
let layout = readFileSync(join(TMP, 'app', 'layout.tsx'), 'utf8');
layout = replaceExact(layout, "import { getSnapshot } from '@/lib/snapshot';\n", '', 'the getSnapshot import');
layout = replaceExact(layout, "export const dynamic = 'force-dynamic';\nexport const maxDuration = 60;\n", '', 'the dynamic/maxDuration exports');
layout = replaceExact(
  layout,
  '  let initial: Snapshot | null = null;\n  try {\n    initial = await getSnapshot();\n  } catch {\n    initial = null;\n  }\n',
  '  // static export for the APK: the client fetches the board (components/SnapshotProvider.tsx)\n  const initial: Snapshot | null = null;\n',
  'the server snapshot fetch',
);
// Capacitor's local server answers every extension-less path with /index.html — the dashboard's
// HTML. A WebView that restarts on a deep path (/import) would then show the dashboard under the
// wrong tab, so anything but "/" starts over at "/" before React runs.
layout = replaceExact(
  layout,
  '      <body>\n',
  '      <body>\n        <script dangerouslySetInnerHTML={{ __html: "if(location.pathname!==\'/\')location.replace(\'/\')" }} />\n',
  'the <body> tag',
);
writeFileSync(join(TMP, 'app', 'layout.tsx'), layout);

writeFileSync(
  join(TMP, 'next.config.mjs'),
  `/** generated by scripts/build-app-web.mjs */\nexport default { reactStrictMode: true, output: 'export', images: { unoptimized: true } };\n`,
);

// 3) export
const env = {
  ...process.env,
  NEXT_PUBLIC_API_BASE: base,
  NEXT_PUBLIC_IN_APP: '1',
  NEXT_PUBLIC_BOT_USERNAME: process.env.NEXT_PUBLIC_BOT_USERNAME || 'MyKasbai_bot',
  NEXT_TELEMETRY_DISABLED: '1',
};
const r = spawnSync(process.execPath, [join(ROOT, 'node_modules', 'next', 'dist', 'bin', 'next'), 'build'], { cwd: TMP, env, stdio: 'inherit' });
if (r.status !== 0) process.exit(r.status ?? 1);

// 4) assemble android-app/dist
rmSync(DIST, { recursive: true, force: true });
cpSync(join(TMP, 'out'), DIST, { recursive: true });
for (const f of ['index.html', 'import.html', 'alerts.html', 'game.html', 'live.html']) {
  if (!existsSync(join(DIST, f))) {
    console.error(`build-app-web: ${f} missing from the bundle`);
    process.exit(1);
  }
}
console.log(`\nAPK web bundle ready in android-app/dist (API: ${base})`);
